######################################################################
# Automatically generated by qmake (3.0) ?? 1? 10 14:53:53 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Calculator
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h
SOURCES += CalculatorDialog.cpp main.cpp
