######################################################################
# Automatically generated by qmake (3.0) ?? 1? 9 17:22:30 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Parent
INCLUDEPATH += .

# Input
SOURCES += Parent.cpp
