######################################################################
# Automatically generated by qmake (3.0) ?? 1? 11 14:44:53 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Login
INCLUDEPATH += .

# Input
HEADERS += LoginDialog.h ui_LoginDialog.h
FORMS += LoginDialog.ui
SOURCES += LoginDialog.cpp main.cpp
