######################################################################
# Automatically generated by qmake (3.0) ?? 1? 11 10:26:58 2018
######################################################################
QT += widgets

TEMPLATE = app
TARGET = Calculator2
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h ui_CalculatorDialog.h
FORMS += CalculatorDialog.ui
SOURCES += CalculatorDialog.cpp main.cpp



