######################################################################
# Automatically generated by qmake (3.0) ?? 1? 16 14:57:05 2018
######################################################################

TEMPLATE = app
TARGET = Semaphore
INCLUDEPATH += .

# Input
SOURCES += main.cpp
