######################################################################
# Automatically generated by qmake (3.0) ?? 1? 10 17:19:11 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Time
INCLUDEPATH += .

# Input
HEADERS += TimeDialog.h
SOURCES += main.cpp TimeDialog.cpp
