######################################################################
# Automatically generated by qmake (3.0) ?? 1? 11 11:41:45 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Time2
INCLUDEPATH += .

# Input
HEADERS += TimeDialog.h ui_TimeDialog.h
SOURCES += main.cpp TimeDialog.cpp
