######################################################################
# Automatically generated by qmake (3.0) ?? 1? 9 14:39:48 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Hello
INCLUDEPATH += .

# Input
SOURCES += Hello.cpp
