######################################################################
# Automatically generated by qmake (3.0) ?? 1? 9 16:38:45 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Button
INCLUDEPATH += .

# Input
SOURCES += Button.cpp
