######################################################################
# Automatically generated by qmake (3.0) ?? 1? 10 11:45:36 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Change
INCLUDEPATH += .

# Input
SOURCES += Change.cpp
