######################################################################
# Automatically generated by qmake (3.0) ?? 1? 10 10:04:21 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Close
INCLUDEPATH += .

# Input
SOURCES += Close.cpp
