######################################################################
# Automatically generated by qmake (3.0) ?? 1? 9 14:39:48 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

HEADERS += calc.h
SOURCES +=  calc.cpp test.cpp

